"""Database initialization

Revision ID: ad27d7e1c84d
Revises: 
Create Date: 2025-12-05 01:16:58.882296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pandas as pd


# revision identifiers, used by Alembic.
revision: str = 'ad27d7e1c84d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.BIGINT(), nullable=True, primary_key=True, autoincrement=True),
    sa.Column('age', sa.BIGINT(), nullable=True),
    sa.Column('sport_licence', sa.TEXT(), nullable=True),
    sa.Column('niveau_etude', sa.TEXT(), nullable=True),
    sa.Column('smoker', sa.TEXT(), nullable=True),
    sa.Column('revenu_estime_mois', sa.BIGINT(), nullable=True),
    sa.Column('situation_familiale', sa.TEXT(), nullable=True),
    sa.Column('historique_credits', sa.FLOAT(), nullable=True),
    sa.Column('risque_personnel', sa.FLOAT(), nullable=True),
    sa.Column('date_creation_compte', sa.FLOAT(), nullable=True),
    sa.Column('score_credit', sa.FLOAT(), nullable=True),
    sa.Column('loyer_mensuel', sa.FLOAT(), nullable=True),
    sa.Column('montant_pret', sa.FLOAT(), nullable=True),
    sa.Column('imc', sa.FLOAT(), nullable=True)
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)

    raw_dataset = pd.read_csv("data/dataset.csv")

    encoded_dataset = raw_dataset.copy()

    encoded_dataset["date_creation_compte"] =  pd.to_datetime(encoded_dataset['date_creation_compte'])
    encoded_dataset["date_creation_compte"] =  encoded_dataset["date_creation_compte"].apply(lambda x: x.timestamp())

    ## Autres catégories
    # encoded_dataset = pd.get_dummies(encoded_dataset)

    # Nettoyage
    cleaned_dataset = encoded_dataset.drop_duplicates(inplace=False)
    num_columns=["age", "historique_credits", "revenu_estime_mois", "risque_personnel", "score_credit", "loyer_mensuel", "date_creation_compte", "montant_pret"]
    cleaned_dataset[num_columns] = cleaned_dataset[num_columns].fillna(value=cleaned_dataset[num_columns].median(), inplace=False) 

    cleaned_dataset = cleaned_dataset.dropna(subset=['situation_familiale'], inplace=False) 

    cleaned_dataset = cleaned_dataset.drop(cleaned_dataset.loc[cleaned_dataset["loyer_mensuel"] < 0.0].index, inplace=False)

    threshold = 1.5

    def find_outliers(col):
        Q1 = col.quantile(0.25)
        Q3 = col.quantile(0.75)
        IQR = Q3 - Q1
        outliers = cleaned_dataset[(col < Q1 - threshold * IQR) | (col > Q3 + threshold * IQR)]
        return outliers

    poids_outliers = find_outliers(cleaned_dataset["poids"])
    cleaned_dataset = cleaned_dataset.drop(poids_outliers.index)

    taille_outliers = find_outliers(cleaned_dataset["taille"])
    cleaned_dataset = cleaned_dataset.drop(taille_outliers.index)

    revenu_outliers = find_outliers(cleaned_dataset["revenu_estime_mois"])
    cleaned_dataset = cleaned_dataset.drop(revenu_outliers.index)

    pret_outliers = find_outliers(cleaned_dataset["montant_pret"])
    cleaned_dataset = cleaned_dataset.drop(pret_outliers.index)

    # Mise en conformité
    final_dataset = cleaned_dataset.copy()

    final_dataset["imc"] = final_dataset.apply(lambda x: x["poids"] / ((x["taille"] / 100) ** 2), axis=1)
    print(final_dataset)

    final_dataset = final_dataset.drop(columns=["nom", "prenom", "sexe", "nationalité_francaise", "taille", "poids", "region"])

    final_dataset.to_sql("loans",  op.get_bind(), if_exists="replace", index=True, index_label="id")

    final_dataset.to_csv('data/cleaned_dataset.csv')

    print("Le DataFrame a été inséré dans la BDD")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.BIGINT(), nullable=True),
    sa.Column('age', sa.BIGINT(), nullable=True),
    sa.Column('sport_licence', sa.TEXT(), nullable=True),
    sa.Column('niveau_etude', sa.TEXT(), nullable=True),
    sa.Column('smoker', sa.TEXT(), nullable=True),
    sa.Column('revenu_estime_mois', sa.BIGINT(), nullable=True),
    sa.Column('situation_familiale', sa.TEXT(), nullable=True),
    sa.Column('historique_credits', sa.FLOAT(), nullable=True),
    sa.Column('risque_personnel', sa.FLOAT(), nullable=True),
    sa.Column('date_creation_compte', sa.FLOAT(), nullable=True),
    sa.Column('score_credit', sa.FLOAT(), nullable=True),
    sa.Column('loyer_mensuel', sa.FLOAT(), nullable=True),
    sa.Column('montant_pret', sa.FLOAT(), nullable=True),
    sa.Column('imc', sa.FLOAT(), nullable=True)
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    # ### end Alembic commands ###
